
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    driver-class-name: org.postgresql.Driver
    username: ridwaan
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

